import 'package:freezed_annotation/freezed_annotation.dart';

part 'ai_models.freezed.dart';
part 'ai_models.g.dart';

/// Represents the role of a message in a conversation.
enum ChatRole {
  /// System prompt to guide the AI behavior.
  system,

  /// Message sent by the user.
  user,

  /// Message generated by the AI assistant.
  assistant,

  /// Tool or function call result.
  tool,
}

/// Represents a single message in a chat conversation.
@freezed
class ChatMessage with _$ChatMessage {
  const factory ChatMessage({
    /// The role of the message sender.
    required ChatRole role,

    /// The content of the message.
    required String content,

    /// Optional timestamp for the message.
    DateTime? timestamp,

    /// Optional metadata associated with the message.
    Map<String, dynamic>? metadata,

    /// Optional tool calls if this is an assistant message.
    List<ToolCall>? toolCalls,
  }) = _ChatMessage;

  factory ChatMessage.fromJson(Map<String, dynamic> json) =>
      _$ChatMessageFromJson(json);
}

/// Configuration for an AI chat request.
@freezed
class ChatRequest with _$ChatRequest {
  const factory ChatRequest({
    /// List of messages in the conversation.
    required List<ChatMessage> messages,

    /// Model-specific parameters (temperature, top_p, etc.).
    @Default(ChatParameters()) ChatParameters parameters,

    /// Whether to stream the response.
    @Default(false) bool stream,

    /// Optional system prompt to override the default one.
    String? systemPrompt,

    /// Optional tools/functions available to the model.
    List<AITool>? tools,
  }) = _ChatRequest;

  factory ChatRequest.fromJson(Map<String, dynamic> json) =>
      _$ChatRequestFromJson(json);
}

/// Model parameters for AI generation.
@freezed
class ChatParameters with _$ChatParameters {
  const factory ChatParameters({
    /// Temperature for randomness (0.0 to 2.0).
    @Default(0.7) double temperature,

    /// Top P for nucleus sampling (0.0 to 1.0).
    @Default(1.0) double topP,

    /// Maximum number of tokens to generate.
    int? maxTokens,

    /// Penalize frequent tokens.
    @Default(0.0) double frequencyPenalty,

    /// Penalize already present tokens.
    @Default(0.0) double presencePenalty,

    /// Seed for deterministic output.
    int? seed,

    /// Stop sequences to end generation.
    List<String>? stop,
  }) = _ChatParameters;

  factory ChatParameters.fromJson(Map<String, dynamic> json) =>
      _$ChatParametersFromJson(json);
}

/// Represents a complete response from an AI provider.
@freezed
@Freezed(makeCollectionsUnmodifiable: false)
class ChatResponse with _$ChatResponse {
  const factory ChatResponse({
    /// The generated message.
    required ChatMessage message,

    /// Usage statistics for the request.
    ChatUsage? usage,

    /// Finish reason (e.g., 'stop', 'length').
    String? finishReason,

    /// The raw response from the provider.
    // @JsonKey(includeFromJson: false, includeToJson: false)
    Object? rawResponse,
  }) = _ChatResponse;

  factory ChatResponse.fromJson(Map<String, dynamic> json) =>
      _$ChatResponseFromJson(json);
}

/// Represents a chunk of a streamed response.
@freezed
class ChatStreamChunk with _$ChatStreamChunk {
  const factory ChatStreamChunk({
    /// The incremental content chunk.
    String? content,

    /// Incremental tool call chunks.
    List<ToolCallChunk>? toolCallChunks,

    /// Finish reason if the stream ended.
    String? finishReason,

    /// Usage if provided in the final chunk.
    ChatUsage? usage,
  }) = _ChatStreamChunk;

  factory ChatStreamChunk.fromJson(Map<String, dynamic> json) =>
      _$ChatStreamChunkFromJson(json);
}

/// Token usage statistics.
@freezed
class ChatUsage with _$ChatUsage {
  const factory ChatUsage({
    @Default(0) int promptTokens,
    @Default(0) int completionTokens,
    @Default(0) int totalTokens,
  }) = _ChatUsage;

  factory ChatUsage.fromJson(Map<String, dynamic> json) =>
      _$ChatUsageFromJson(json);
}

/// Definition of a tool/function available to the AI.
@freezed
class AITool with _$AITool {
  const factory AITool({
    required String name,
    required String description,
    required Map<String, dynamic> parameters,
  }) = _AITool;

  factory AITool.fromJson(Map<String, dynamic> json) => _$AIToolFromJson(json);
}

/// Represents a call to a tool from the AI.
@freezed
class ToolCall with _$ToolCall {
  const factory ToolCall({
    required String id,
    required String name,
    required String arguments,
  }) = _ToolCall;

  factory ToolCall.fromJson(Map<String, dynamic> json) =>
      _$ToolCallFromJson(json);
}

/// Represents a chunk of a tool call in a stream.
@freezed
class ToolCallChunk with _$ToolCallChunk {
  const factory ToolCallChunk({
    required int index,
    String? id,
    String? name,
    String? arguments,
  }) = _ToolCallChunk;

  factory ToolCallChunk.fromJson(Map<String, dynamic> json) =>
      _$ToolCallChunkFromJson(json);
}
