name: Publish to Pub.dev

on:
  push:
    branches:
      - main

jobs:
  publish:
    permissions:
      id-token: write # Required for OIDC authentication
      contents: read
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1